### ISSUE TITLE
details on filenames

### ISSUE THREAD

**Issue by dsernst** [amussey/simplenote-to-git#2]
Can you provide the skinny on how the files are named? I see at least 4 different patterns:

Most files are 32-character hexadecimal:
1. `06f0c1ac11da4018aae548b9765496f0`
2. `601e5fe2bb5d46cb9088eb63ac1c1f94`
3. `0752bf604a9149b5a4a099c5874c381f`
4. `6041dba237f6476ca097c4775fc590cd`

About two dozen files prefixed with `agtzaW1wbGUtbm90ZXINCxIETm90ZRjy` + 8 more random characters
1. `agtzaW1wbGUtbm90ZXINCxIETm90ZRjyiZcKDA`
2. `agtzaW1wbGUtbm90ZXINCxIETm90ZRjyjp4NDA`

This strange mix of what looks like base 64 and plain text:

1 . `ahFzfnNpbXBsZS1ub3RlLWhyZHINCxIEVXNlchjwhJkKDA:welcomeNote-Mac`

and then a few with hyphens in the filename:
1. `896993d8-cd3a-4081-bb4a-66f7fcd3e0ee`
2. `d602e7e0-ad24-419c-a6da-14f0cbc02386`

Is there significance behind each of these? Rhyme or reason? Historical artifacts as Simplenote's underlying infrastructure changed?

**Comment by amussey** [comment]
For this script, all the files are named based on their `key`/unique identifier in the Simplenote database/response.  "Historical artifacts as Simplenote's underlying infrastructure changed" is probably the most accurate explanation!
